title: Schematics & BoardViewers
description: A public site with free content about hardware to help technicians and PC enthusiats that want to fix their hardware
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
